name: Build and Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build-type: [Debug, Release]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2

    - uses: lukka/get-cmake@latest

    - name: Install Vcpkg
      uses: johnwason/vcpkg-action@v5
      with:
        manifest-dir: ${{ github.workspace }} # Set to directory containing vcpkg.json
        revision: '501db0f17ef6df184fcdbfbe0f87cde2313b6ab1'

    - name: Create Build Environment
      run: cmake -E make_directory ${{ github.workspace }}/build
    
    - name: Configure CMake
      shell: bash
      run: cmake ${{ github.workspace }} -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -B ${{ github.workspace }}/build
    
    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build-type }}
    
    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest --verbose