name: Build, Package and Upload

on:
  release:
    types: [created]  # Trigger this workflow on release creation

jobs:
  build-and-package:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [x86, x64]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - uses: lukka/get-cmake@latest

    - name: Install Vcpkg
      uses: johnwason/vcpkg-action@v5
      with:
        manifest-dir: ${{ github.workspace }} # Set to directory containing vcpkg.json
        revision: '501db0f17ef6df184fcdbfbe0f87cde2313b6ab1'

    - name: Create Build Environment
      run: cmake -E make_directory ${{ github.workspace }}/build
    
    - name: Configure CMake
      shell: bash
      run: cmake ${{ github.workspace }} -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -B ${{ github.workspace }}/build
    
    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build-type }}

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest --verbose

    - name: Install
      run: cmake --install ${{ github.workspace }}/build --prefix build/install
    
    - name: Package
      run: |
        cd build/install
        tar czf ../../${{ matrix.os }}-${{ matrix.architecture }}-package.tar.gz *

    - name: Upload
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}  # This pulls from the release event
        asset_path: ${{ github.workspace }}/${{ matrix.os }}-${{ matrix.architecture }}-package.tar.gz
        asset_name: ${{ matrix.os }}-${{ matrix.architecture }}-package.tar.gz
        asset_content_type: application/gzip